/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        bug: "#79984F",
        lightBug: "#A4C8A1",
        dark: "#56443D",
        lightDark: "#8E7B6A",
        dragon: "#3F4080",
        lightDragon: "#6F6FBB",
        electric: "#AB953E",
        lightElectric: "#E3C177",
        fairy: "#A96CA4",
        lightFairy: "#D4A6B6",
        fighting: "#B05633",
        lightFighting: "#D38A63",
        fire: "#B64039",
        lightFire: "#D8827E",
        flying: "#728288",
        lightFlying: "#A3B3B3",
        ghost: "#43406F",
        lightGhost: "#75748C",
        grass: "#769669",
        lightGrass: "#A4C8A1",
        ground: "#7D4C3F",
        lightGround: "#BCA69C",
        ice: "#61A1AC",
        lightIce: "#A1D2D8",
        normal: "#A8A878",
        lightNormal: "#D5D59C",
        poison: "#6D3DA3",
        lightPoison: "#A68DC2",
        psychic: "#D14C45",
        lightPsychic: "#EBA1A0",
        rock: "#968053",
        lightRock: "#B8B18C",
        steel: "#7A7A7A",
        lightSteel: "#B2B2B2",
        water: "#4668A3",
        lightWater: "#A1C6E0",
      },
    },
  },
  plugins: [],
  safelist: [
    "bg-bug",
    "bg-lightBug",
    "bg-dark",
    "bg-lightDark",
    "bg-dragon",
    "bg-lightDragon",
    "bg-electric",
    "bg-lightElectric",
    "bg-fairy",
    "bg-lightFairy",
    "bg-fighting",
    "bg-lightFighting",
    "bg-fire",
    "bg-lightFire",
    "bg-flying",
    "bg-lightFlying",
    "bg-ghost",
    "bg-lightGhost",
    "bg-grass",
    "bg-lightGrass",
    "bg-ground",
    "bg-lightGround",
    "bg-ice",
    "bg-lightIce",
    "bg-normal",
    "bg-lightNormal",
    "bg-poison",
    "bg-lightPoison",
    "bg-psychic",
    "bg-lightPsychic",
    "bg-rock",
    "bg-lightRock",
    "bg-steel",
    "bg-lightSteel",
    "bg-water",
    "bg-lightWater",
  ],
};
